### ISSUE TITLE
org.bimserver.shared.reflector.ReflectorException

### ISSUE THREAD

**Issue by lileixing** [opensourceBIM/BimServerJavaClientDemo#4]
public void start() {
		JsonBimServerClientFactory factory;
		try {
			factory = new JsonBimServerClientFactory("http://localhost:8080/bimserverwar-1.5.111");
			try {
				BimServerClient client = factory.create(new UsernamePasswordAuthenticationInfo("admin@qq.com", "admin"));
				doWithClient(client);
			} catch (ServiceException e) {
				// TODO Auto-generated catch block
			} catch (ChannelConnectionException e) {
				e.printStackTrace();
			}
		} catch (BimServerClientException e) {
			e.printStackTrace();
		}
	}

Exception in thread "main" org.bimserver.shared.reflector.ReflectorException: java.lang.UnsupportedOperationException: "3c66c1c9b60573dad20d82530c15f4fe1669db724dd9040b24afb68953d18c8a6d826644a48237565f44e9db6874a36d"
	at org.bimserver.shared.json.JsonReflector.callMethod(JsonReflector.java:106)
	at org.bimserver.generated.AuthInterfaceImpl1.login(AuthInterfaceImpl1.java)
	at org.bimserver.client.BimServerClient.authenticate(BimServerClient.java:130)
	at org.bimserver.client.BimServerClient.connect(BimServerClient.java:122)
	at org.bimserver.client.BimServerClient.setAuthentication(BimServerClient.java:115)
	at org.bimserver.client.json.JsonBimServerClientFactory.create(JsonBimServerClientFactory.java:68)
	at com.starli.bim.ifc.BaseApp.start(BaseApp.java:19)
	at com.starli.bim.ifc.App.main(App.java:24)
Caused by: java.lang.UnsupportedOperationException: "3c66c1c9b60573dad20d82530c15f4fe1669db724dd9040b24afb68953d18c8a6d826644a48237565f44e9db6874a36d"
	at org.bimserver.shared.json.JsonConverter.fromJson(JsonConverter.java:295)
	at org.bimserver.shared.json.JsonReflector.callMethod(JsonReflector.java:92)
	... 7 more

**Comment by rubendel** [comment]
Fixed in 1.5.113, since you did not mention the version you are using, I am closing the issue.
